allowBuilds:
  '@playwright/browser-chromium': true
minimumReleaseAgeExclude:
  - playwright-core@1.62.1
overrides:
  'playwright-core': '^1.62.1' # try removing once @vscode/test-cli upgrades > 0.0.15
  'serialize-javascript': '^7.0.5' # try removing once @vscode/test-cli upgrades > 0.0.15